In [4]:
import os
os.environ["MKL_THREADING_LAYER"] = "GNU"
import numpy
import theano
import theano.tensor as T
from theano import pp
x = T.dscalar('x')
y = x ** 2
gy = T.grad(y, x)
pp(gy)  # print out the gradient prior to optimization
f = theano.function([x], gy)
print(f(8))

16.0


In [5]:
x = T.dmatrix('x')
s = T.sum(1 / (1 + T.exp(-x)))
gs = T.grad(s, x)
dlogistics = theano.function([x], gs)
print(dlogistics([[0, 1], [-1, -2]]))

[[0.25       0.19661193]
 [0.19661193 0.10499359]]


In [8]:
x = T.dvector('x')
y = x**2
J, updates = theano.scan(lambda i, y, x: T.grad(y[i],x), sequences=T.arange(y.shape[0]), non_sequences=[y, x])
f = theano.function([x], J, updates=updates)
print(f([4, 3]))

[[8. 0.]
 [0. 6.]]


In [9]:
x = T.dvector('x')
y = x**2
cost = T.sum(y)
gy = T.grad(cost, x)
H, updates = theano.scan(lambda i, y, x: T.grad(gy[i], x), sequences=T.arange(gy.shape[0]), non_sequences=[gy, x])
f = theano.function([x], H, updates=updates)
print(f([4, 4]))

[[2. 0.]
 [0. 2.]]
